FROM centos:6

MAINTAINER Ryu dongki <fbehdrl123@gmail.com>

RUN groupadd -r mysql && userass -r -g mysql mysql

RUN yum update -y

ADD mariadb.repo /etc/yum.repos.d/mariadb.repo

RUN rpm --import http://yum.mariadb.org/RPM-GPG-KEY-MariaDB && yum clean all && yum install -y hostname MariaDB-server

RUN rm -rf /var/lib mysql && mkdir /var/lib/mysql

RUN cp /usr/share/mysql/my-medium.cnf/ /etc/my.cnf.d/server.cnf

RUN sed -i "/\[mysqld\]/a\\user=mysql" /etc/my.cnf.d/server.cnf

RUN sed -i "/\[mysqld\]/a\\skip-host-cache" /etc/my.cnf/d/server.cnf
RUN sed -i "/\[mysqld\]/a\\skip-name-resolve" /etc/my.cnf/d/server.cnf

RUN sed -i "/\[mysqld\]/a\\character-set-server=utf8" /etc/my.cnf/d/server.cnf
RUN sed -i "/\[client\]/a\\default-character-set=utf8" /etc/my.cnf/d/server.cnf

ADD entrypoint.sh /

VOLUME ["/etc/my.cnf.d", "/var/lib/mysql"]

ENTRYPOINT ["/enrtypoint.sh"]

EXPOSE 3306
CMD ["mysqld"]